# PANDAS

In [1]:
#Creating numPy and pandas Package
import pandas as pd
import numpy as np

In [4]:
value=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['Row1','Row2','Row3','Row4','Row5'],columns=['Column1','Column2','Column3','Column4'])

In [5]:
value.head()

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [9]:
 ## accessing the elements
    ## 1. .loc 2. .iloc
type(value.loc['Row1'])

pandas.core.series.Series

In [11]:
type(value.iloc[0:3,0:2])

pandas.core.frame.DataFrame

In [16]:
value.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [18]:
value.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [20]:
value['Column1'].value_counts()

0     1
4     1
8     1
12    1
16    1
Name: Column1, dtype: int64

In [21]:
value['Column2'].unique()

array([ 1,  5,  9, 13, 17])

# READING IN PANDAS

In [23]:
value.to_csv('Test1.CSV')

In [32]:
test_value=pd.read_csv('Test1.CSV',sep=',')

In [33]:
test_value.head()

  Unnamed: 0  Column1  Column2  Column3  Column4
0       Row1        0        1        2        3
1       Row2        4        5        6        7
2       Row3        8        9       10       11
3       Row4       12       13       14       15
4       Row5       16       17       18       19

## CSV

In [38]:
from io import StringIO, BytesIO

In [39]:
data =('col1,col2,col3\n'
      'x,y,1\n'
      'a,b,2\n'
      'c,d,3')

In [40]:
type(data)

str

In [41]:
pd.read_csv(StringIO(data))

  col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [42]:
## Read From specific Columns

In [43]:
pd.read_csv(StringIO(data),usecols=['col1','col3'])

  col1  col3
0    x     1
1    a     2
2    c     3

In [44]:
data1=('a,b,c\n'
      '1,apple,bat\n'
      '2,orange,ball')

In [45]:
data1

'a,b,c\n1,apple,bat\n2,orange,ball'

In [46]:
pd.read_csv(StringIO(data1))

   a       b     c
0  1   apple   bat
1  2  orange  ball

In [47]:
pd.read_csv(StringIO(data1),index_col=False)

   a       b     c
0  1   apple   bat
1  2  orange  ball

In [48]:
pd.read_csv(StringIO(data1),usecols=['b','c'],index_col=False)

        b     c
0   apple   bat
1  orange  ball